server:
  port: 9999
  servlet:
    context-path: /gjob-providers
spring:
  application:
    name: gjob-providers
  datasource:
    url: jdbc:mysql://192.168.31.222/fourthaction
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 5000
  data:
    mongodb:
      database: test
      host: 127.0.0.1
      port: 27017
    solr:
      host: http://192.168.31.236:8091/solr/mycore
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /1710b
logging:
  file: ./logback.log

